apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-database
  template:
    metadata:
      labels:
        app: oracle-database
    spec:
      containers:
        - name: oracle-database-container
          image: oracleinanutshell/oracle-xe-11g:latest
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              value: oracle
          volumeMounts:
            - name: oracle-volume
              mountPath: /opt/oracle/oradata
      volumes:
        - name: oracle-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-database-service
spec:
  selector:
    app: oracle-database
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
  type: ClusterIP