apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
        - name: postgres-database-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database-service
spec:
  selector:
    app: postgres-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP