apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    app: spring-app
spec:
  selector:
    app: spring-app
    # version: v1
  ports:
    - name: http
      port: 80
      targetPort: 8086
  type: LoadBalancer