apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
        version: v1
    spec:
      containers:
        - name: spring-app-container
          image: ghcr.io/octodemo/java-springboot-demo:77
          ports:
            - containerPort: 8086
          env:
            - name: DB_URL
              value: jdbc:postgresql://database:5432/postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PASSWORD
              value: postgres
            - name: CHANGELOG_VERSION
              value: changelog_version-3.3.xml
      imagePullSecrets:
        - name: your-registry-secret