apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-spring-app-service
  labels:
    app: spring-app
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.springAppService.type }}
  selector:
    app: spring-app
  {{- include "my-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.springAppService.ports | toYaml | nindent 2 }}