apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-v2
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.v2.replicas }}
  selector:
    matchLabels:
      app: spring-app
    {{- include "my-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: spring-app
        version: v2
      {{- include "my-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_URL
          value: {{ quote .Values.v2.springAppContainer.env.dbUrl }}
        - name: USER_NAME
          value: {{ quote .Values.v2.springAppContainer.env.userName }}
        - name: PASSWORD
          value: {{ quote .Values.v2.springAppContainer.env.password }}
        - name: CHANGELOG_VERSION
          value: {{ quote .Values.v2.springAppContainer.env.changelogVersion }}
        - name: REDIS_HOST
          value: {{ quote .Values.v2.springAppContainer.env.redisHost }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.v2.springAppContainer.image.repository }}:{{ .Values.v2.springAppContainer.image.tag
          | default .Chart.AppVersion }}
        name: spring-app-container
        ports:
        - containerPort: 8086
        resources: {{- toYaml .Values.v2.springAppContainer.resources | nindent 10 }}
      imagePullSecrets:
      - name: your-registry-secret