name: CD

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "tsvi-rg"
  CLUSTER_NAME: "tsvi-aks"
  DEPLOYMENT_MANIFEST_PATH: "./deployments"

jobs:
  staging:
    permissions:
      actions: read
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    
    runs-on: ubuntu-latest
    environment: STAGE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to Kubernetes [STAGING ENVIRONMENT]
        run: |
          echo "kubectl apply -f deployments/"
      
      - name: UAT TESTS [STAGING ENVIRONMENT]
        run: |
          echo "running UAT tests with version tag: ${{ inputs.image_tag }}"

      - name: SMOKE TESTS [STAGING ENVIRONMENT]
        run: |
          echo "running SMOKE tests with version tag: ${{ inputs.image_tag }}"

      - name: PERFORMANCE TESTS [STAGING ENVIRONMENT]
        run: |
          echo "running PERFORMANCE tests with version tag: ${{ inputs.image_tag }}"
  
  production:
    permissions:
      actions: read
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    
    runs-on: ubuntu-latest
    environment: PROD
    needs: [staging]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: 'Az CLI Login via OIDC'
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # - name: Deploy to Kubernetes [PRODUCTION ENVIRONMENT]
      #   run: |
      #     kubectl apply -f deployments/
