name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string

jobs:
  deploy_staging:
    runs-on: deployment_server
    environment: STAGE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployments/
    strategy:
      matrix:
        runner: [ARM64]
  
  deploy_production:
    runs-on: deployment_server
    environment: PROD
    needs: [deploy_staging]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployments/
    strategy:
      matrix:
        runner: [ARM64]