name: CD

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: STAGE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          echo "kubectl apply -f deployments/ tags: ${{ github.event.inputs.tags }}"
      # print out the tags from the CI workflow
  
  production:
    runs-on: ubuntu-latest
    environment: PROD
    needs: [staging]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          echo "kubectl apply -f deployments/"