name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment: STAGE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          echo "kubectl apply -f deployments/"
  
  deploy_production:
    runs-on: ubuntu-latest
    environment: PROD
    needs: [deploy_staging]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          echo "kubectl apply -f deployments/""