name: CD

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: STAGE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          echo "kubectl apply -f deployments/ deployment tag: ${{ inputs.image_tag }}"
  
  production:
    runs-on: ubuntu-latest
    environment: PROD
    needs: [staging]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: |
          echo "kubectl apply -f deployments/"